### ISSUE TITLE
Erro na escrita de arquivos

### ISSUE THREAD

**Issue by LJC-DB** [rjmalves/idecomp#10]
Como o primeiro valor de registro está sendo salvo como uma lista vazia, com os dados do arquivo estando nos registros subsequentes, a função `write` não é capaz de escrever o arquivo.

Ao pular esta primeira linha, a escrita ocorreu conforme o esperado.

**Comment by rjmalves** [comment]
Olá. O erro está relacionado a escrita de qual arquivo? Pode fornecer alguma informação adicional sobre a situação em que ocorreu o erro?

**Comment by LJC-DB** [comment]
Uma simples operação de leitura seguida por uma de escrita é o suficiente para causar o problema (editando ou não algum valor).
Segue um simples código de exemplo do problema:
```
from idecomp.decomp.dadger import Dadger
dadger = Dadger.le_arquivo(r"C:\Users\Leonardo\Documents\teste_escreve_decompe/DC202112-sem1/", "DADGER.RV0")
for ct in dadger.ct():
    ct.cvus = [0,0,0]
dadger.escreve_arquivo(r"C:\Users\Leonardo\Documents\teste_escreve_decompe/DC202112-sem1/", "DADGER2.RV0")
```

Que leva ao erro 
```
Exception has occurred: TypeError
write() argument must be str, not list
```
na função `escreve_arquivo`

Ao acessar o valor `dadger.data.first.data` tem como saída uma lista vazia, enquanto em `dadger.data.first.next.data` está a primeira linha do arquivo.
Acredito que a lista vazia seja criada como um registro vazio para facilitar a leitura e que não está sendo apagado após completá-la nem sendo desconsiderado para a função escrita.

**Comment by rjmalves** [comment]
Encontrei o problema. É em uma das dependências utilizadas: [cfinterface](https://github.com/rjmalves/cfi). O bug já foi corrigido na versão [1.0.1](https://github.com/rjmalves/cfi/releases/tag/v1.0.1) e a dependência será atualizada na próxima release da idecomp, que deve ser a 0.0.47. Deve ser lançada ainda hoje, mais tarde.

**Comment by rjmalves** [comment]
Corrigido na versão [0.0.47](https://github.com/rjmalves/idecomp/releases/tag/v0.0.47)
